### ISSUE TITLE
Determine number of cameras and other VR materials needed for best streaming of the workshops

### ISSUE THREAD

**Issue by ckoroma** [deptofdefense/hackThePlane#10]
- Cameras
- Backdrops?
-Streaming boxes to control lights?
- lights?
- wifi boosters?

**Comment by ckoroma** [comment]
@RoRoRah you recommended: 
Photo Box, SAMTIAN 24x24x24 Inches Professional Light Box 126 LED Light Shooting Tent Table Top Photography Lighting Kit with 6 Background Papers https://www.amazon.com/dp/B077HPJG5X/ref=cm_sw_r_cp_api_i_-O.8Eb176EE4Z

This would be good for the HAS models yes?

**Comment by ckoroma** [comment]
@danallendds @RoRoRah this is the one recommended by Dan.  So order the 32" cube for the lego models? Will this one allow for the depth RoRo recommends?  If so please also add to the parts list

The Lego kits might fit in the 24" cube. There's this one that's 32" cube... pretty sure each kit would fit in one of these.
https://www.amazon.com/dp/B071VW8BX2/ref=sspa_dk_detail_1?pd_rd_i=B06XQ52YFY&pd_rd_w=G6xWn&pf_rd_p=48d372c1-f7e1-4b8b-9d02-4bd86f5158c5&pd_rd_wg=ShPyY&pf_rd_r=ZH5XDBP0Q25B0CV0F24G&pd_rd_r=f4e74b79-7fdb-4244-b66e-51c6e6324604&spLa=ZW5jcnlwdGVkUXVhbGlmaWVyPUEyRUU0QlJFOTc2RTBRJmVuY3J5cHRlZElkPUExMDM2MTc5MkVLS0kySVQ0QTNIWiZlbmNyeXB0ZWRBZElkPUEwMzM0NDIyT0VaQVI2VDlMWUJSJndpZGdldE5hbWU9c3BfZGV0YWlsJmFjdGlvbj1jbGlja1JlZGlyZWN0JmRvTm90TG9nQ2xpY2s9dHJ1ZQ&th=1

**Comment by ckoroma** [comment]
## Let's create a streaming kit for each kit, please add additional items:

### Bricks Kit 1
- [ ] Box (which one?)
- [ ] X cameras
- [ ] X lights, What kind?
- [ ] Cooling fans?

### Bricks Kit 2
- [ ] Box (which one?)
- [ ] X cameras
- [ ] X lights, What kind?
- [ ] Cooling fans?

### Bricks Kit 3
- [ ] Box (which one?)
- [ ] X cameras
- [ ] X lights, What kind?
- [ ] Cooling fans?

### Bricks Kit 4
- [ ] Box (which one?)
- [ ] X cameras
- [ ] X lights, What kind?
- [ ] Cooling fans?

### Bricks Kit 5
- [ ] Box (which one?)
- [ ] X cameras
- [ ] X lights, What kind?
- [ ] Cooling fans?

SimpleSat
- [ ] Box (which one?)
- [ ] X cameras
- [ ] X lights, What kind?
- [ ] Cooling fans?

### CubeSat
- [ ] Box (which one?)
- [ ] X cameras
- [ ] X lights, What kind?
- [ ] Cooling fans?

**Comment by danallendds** [comment]
We've purchased all the things already... it is what it is.
