### ISSUE TITLE
Buy Hotspots?

### ISSUE THREAD

**Issue by ckoroma** [deptofdefense/hackThePlane#22]
Determine if there are hotspots or other items that can help strengthen/separate the wifi for DEFCON virtual environments from the home network.

**Comment by danallendds** [comment]
I think it would be best to plan to run these out of Tulsa University were Nick is at. Perhaps with a bunch of students as SGEs monitoring everything.

**Comment by ckoroma** [comment]
@danallendds are you saying we need to ship all of these to Tulsa? If so we need to make a plan now.  Means we will need to have everything built by 3rd week.

**Comment by danallendds** [comment]
OBE at this point. closing to declutter
