### ISSUE TITLE
Create list of design assets that will implement the BIA brand

### ISSUE THREAD

**Issue by ckoroma** [deptofdefense/hackThePlane#5]
# Preliminary List
- BIA Logo
- BIA stickers
- Zoom Backgrounds
- Twitter and linked in graphics
- DDS.mil page for recruiting
- Twitch backgrounds for printing, possible virtual
- Newsletter Layout

Reference: https://docs.google.com/document/d/1gxWF5aqzctQfwUeOQrtCNOzaNQvhxuBQxhHEqW7_SkY/edit

**Comment by ckoroma** [comment]
-back drops for folks doing official zooms during defcon?

**Comment by matthewdjordan** [comment]
- google slides deck template
- BitA video "hold" graphic
- forum avatar
- email signature (img)
- website hero

**Comment by TimLillis** [comment]
- Graphic overlays for different levels of BitA challenges
- Source videos + and style reference for "digital docents"
- Digital signage for doors in VR space

**Comment by ckoroma** [comment]
converted list to individual issues
