### ISSUE TITLE
FOR VR: We would need to see how DDS is handling queuing and any endpoints that could return us that data/ iframe it into our site. Any documentation for this would be helpful.

### ISSUE THREAD

**Issue by ckoroma** [deptofdefense/hackThePlane#65]
Need to have this detail so I can drop it in the jira ticket for the vendor/

**Comment by zeetwii** [comment]
Right now as a part of the Chat bot we have a function that keeps track of how many active users are on at any given moment.  

Ideally we would like a socket on their side that we could push that number to any time it changes

**Comment by ckoroma** [comment]
Responded that we are not going to do twitch integration
