### ISSUE TITLE
Engine Stop

### ISSUE THREAD

**Issue by royyblume** [deptofdefense/hackThePlane#71]
If there is more than one user in the queue and the engine gets turned off during the first user's turn followed by a switch in turns, the engine will go to the correct state for the second user. However, upon returning to first user's turn (who's plane engine should be shut off), the engine will continue to run. 
Should be able to be fixed if there is a check when switching users: If the user is on question 5.1, engine will be turned off.

**Comment by danallendds** [comment]
When you guys get a chance... try running again through the various users and observe the sound. The fix turned out to be involved because I had to change the engine control .ino file for the mcu to even accept an engine off command.

**Comment by royyblume** [comment]
I tested some things out today. I was able to get the engine to remain stopped by passing "!goto 5.1" (the engine stop question), followed by "!goto 5.3" (when the engine should be back up).

**Comment by danallendds** [comment]
I think this has been fixed... marking as closed.
