### ISSUE TITLE
Determine which lego kits we will use for the Defcon28 workshops

### ISSUE THREAD

**Issue by ckoroma** [deptofdefense/hackThePlane#8]
Need to determine which lego kits we will use for the workshops and procure them

**Comment by ckoroma** [comment]
Reached out to lego on the lego.com website to start dialogue about official engagement and access to new release kits: We are a federal government team called the Defense Digital Service that have been using lego kits for our presence at DEFCON to teach aviation hacking and security. Interested in the new release kit for use this year: technic bell boeing 42113.  Would also like to do some official collabs with lego if possible

**Comment by ckoroma** [comment]
## Possible kits (@danallendds @zeetulsa please review, add, reject, approve).  **Let's pick at least 4 by Friday 06/25, we need to purchase these and start assembly.**

- [x] **LEGO Technic Cargo Plane (42025):** https://www.amazon.com/Lego-42025-Technic-Cargo-Plane/dp/B00F3B48YA/ref=sr_1_117?dchild=1&keywords=technic&qid=1592942043&sr=8-117
- [ ] **Rescue Helicopter:** https://www.lego.com/en-us/product/rescue-helicopter-42092
- [ ] **LEGO Technic Ultralight Helicopter 42057 Advance Building Set:** https://www.amazon.com/LEGO-Technic-Ultralight-Helicopter-Building/dp/B01KIORG4A/ref=sr_1_14?dchild=1&keywords=technic&qid=1592941528&sr=8-14
- [ ] **LEGO Star Wars Poe Dameron's X-Wing Fighter 75273 Building Kit:** https://www.amazon.com/LEGO-Damerons-Fighter-Building-Construction/dp/B07Y8SR9BZ/ref=sr_1_38?dchild=1&keywords=technic&qid=1592941935&sr=8-38
- [x] **LEGO Technic Heavy Lift Helicopter 42052 Advanced Building Toy:** https://www.amazon.com/LEGO-Technic-Helicopter-Advanced-Building/dp/B01E78WKEO/ref=sr_1_107?dchild=1&keywords=technic&qid=1592942043&sr=8-107
- [ ] **LEGO Technic 42040 Fire Plane Building Kit:** https://www.amazon.com/LEGO-Technic-42040-Plane-Building/dp/B00WHXP7LK/ref=pd_pg_c_d_dps_0_6/132-2000513-1601838?_encoding=UTF8&pd_rd_i=B00WHXP7LK&pd_rd_r=bc90ae49-7a06-4056-b63f-775136e793b9&pd_rd_w=xYilR&pd_rd_wg=vFxmQ&pf_rd_p=79ba09e2-b819-4ad0-84ae-fda224067c95&pf_rd_r=Q3HDY12G2803JDNZA5Y3&psc=1&refRID=Q3HDY12G2803JDNZA5Y3
- [x] **LEGO Technic Helicopter 9396:** https://www.amazon.com/LEGO-9396-Technic-Helicopter/dp/B006ZS4SHC/ref=pd_pg_c_d_dps_0_12?_encoding=UTF8&pd_rd_i=B006ZS4SHC&pd_rd_r=bc90ae49-7a06-4056-b63f-775136e793b9&pd_rd_w=xYilR&pd_rd_wg=vFxmQ&pf_rd_p=79ba09e2-b819-4ad0-84ae-fda224067c95&pf_rd_r=Q3HDY12G2803JDNZA5Y3&psc=1&refRID=Q3HDY12G2803JDNZA5Y3
- [ ] **LEGO Technic 42020 Twin-Rotor Helicopter Model Kit:** https://www.amazon.com/dp/B00J4S4EB0/ref=dp_cerb_2
- [ ] **LEGO Technic Display Team Jet 42044 Building Kit:** https://www.amazon.com/LEGO-Technic-Display-42044-Building/dp/B018AIFN50/ref=sr_1_152?dchild=1&keywords=technic&qid=1592942149&sr=8-152
- [ ] **LEGO Technic Jet Plane 9394:** https://www.amazon.com/LEGO-Technic-Jet-Plane-9394/dp/B005VPRGBA/ref=sr_1_156?dchild=1&keywords=technic&qid=1592942149&sr=8-156

**Comment by danallendds** [comment]
In Endor right now I believe are the following:
2 kits - LEGO Technic Cargo Plane (42025):
2 kits -  LEGO Technic Heavy Lift Helicopter 42052 Advanced Building Toy
And then a blue jet, https://www.lego.com/en-us/product/air-race-jet-42066

The  LEGO Technic Helicopter 9396 ^^ would work. The key is that the kit has to be "Power Functions" ready, otherwise we're spending a bunch of unnecessary time trying to fit a motor somewhere... Lego has already done that on Power Function ready kits.

**Comment by zeetwii** [comment]
[LEGO Technic Helicopter 9396](https://www.amazon.com/LEGO-9396-Technic-Helicopter/dp/B006ZS4SHC/)

[LEGO Technic Heavy Lift Helicopter 42052 Advanced Building Toy](https://www.amazon.com/LEGO-Technic-Helicopter-Advanced-Building/dp/B01E78WKEO)

[LEGO Technic Cargo Plane (42025)](https://www.amazon.com/Lego-42025-Technic-Cargo-Plane/dp/B00F3B48YA)

Those are the three that will work as is

**Comment by ckoroma** [comment]
@danallendds and @zeetulsa I need one more kit to purchase. Which one? Twin rotor? Fire plane? It could shoot fire:-)

**Comment by danallendds** [comment]
Cargo Plane, that's my vote

**Comment by ckoroma** [comment]
- On order and on its way to Dan:  LEGO Technic Cargo Plane (42025) https://www.amazon.com/Lego-42025-Technic-Cargo-Plane/dp/B00F3B48YA/ref=sr_1_117?dchild=1&keywords=technic&qid=1592942043&sr=8-117
- On Order and on it's way to Nick: LEGO Technic Heavy Lift Helicopter 42052 Advanced Building Toy https://www.amazon.com/LEGO-Technic-Helicopter-Advanced-Building/dp/B01E78WKEO and then one of the extra motor kits:
https://www.amazon.com/LEGO-Technic-Power-Functions-Motor/dp/B01E78WLCU/

**Comment by ckoroma** [comment]
- On order to Dan Flack: LEGO Technic Helicopter 9396

**Comment by danallendds** [comment]
4th kit to order:
LEGO Technic Heavy Lift Helicopter 42052 Advanced Building Toy: https://www.amazon.com/LEGO-Technic-Helicopter-Advanced-Building/dp/B01E78WKEO/ref=sr_1_107?dchild=1&keywords=technic&qid=1592942043&sr=8-107

Built as the tandem variant.

**Comment by zeetwii** [comment]
@ckoroma Order this one for Kam: [heavy lift helo](https://www.amazon.com/LEGO-Technic-Helicopter-Advanced-Building/dp/B01E78WKEO) 

One of us will build the tandem version, and the other will build the coaxial style

**Comment by ckoroma** [comment]
Perfect, this will go to Kam Tillman.

**Comment by ckoroma** [comment]
Still working with lego on getting the technic bell boeing 42113.  Will update issue if that happens.
