### ISSUE TITLE
Question 4.4

### ISSUE THREAD

**Issue by royyblume** [deptofdefense/hackThePlane#82]
Question 4.4 asks "What valid range of engine speed values can you set now?". I found this a little confusing since the answer is a command that sets the speed, rather than a range of values. An alternative could be "Now that the engine is in debug mode, what new valid engine speed value can you set?" or "Set a new valid engine speed value".

**Comment by danallendds** [comment]
Tim... can you update the slides for a 4 kits on 4-4 to say:
Now that the engine is in debug mode, what new valid engine speed value can you set?

**Comment by danallendds** [comment]
scripts have been updated to reflect the new question:
Now that the engine is in debug mode, what new valid engine speed value can you set?

**Comment by TimLillis** [comment]
edited 4-4 and 4-5 for all workshops.
