### ISSUE TITLE
Determine engineering support needed for lego kit builds

### ISSUE THREAD

**Issue by ckoroma** [deptofdefense/hackThePlane#9]
- Identify skill sets needed
- ways to get the help

**Comment by danallendds** [comment]
The 5 kits we had from last year are in the Endor, in varying pieces of disrepair along with extra parts and the instruction manual. I should probably make a trip into PNT sometime soon and take the kits back to my place to get them operational again.

**Comment by danallendds** [comment]
http://www.brickfinder.net/2020/06/19/lego-technic-2hy-2020-official-images/

^^ Kit 42113 would be super cool, but no idea when it will actually become available.

**Comment by ckoroma** [comment]
## Posted in Slack 06/25/20
@channel Hi Friends (cross posting from the eng channel for those who are not in that one)
The DEFCON 28 team needs your help if you have the skill sets outlined below AND the ability to dedicate at least 50% of your time (more preferred) to help on this effort through the second week of August. If this is you, please DM me. If it is not you and you know of folks who may fit this description, please also DM me.  No One is Coming!

**SKILLS**
Microcontroller programming

- C/Arduino a plus
- I2C protocol a plus
- IRDA comms a plus

Electrical skills

- Soldering
- Wiring
- Rigging motors

Mechanical Skills

- Lego building/modifying
- Build a Lego Kit (examples in the list below) and then hack it so that each of the power function articulation points are directly driven by a dedicated Power Functions motor. In addition, make a stand so that the kit has full range of motion fo the Power Functions (i.e. raise/lower the landing gear):
- 42052: https://www.amazon.com/LEGO-Technic-Helicopter-Advanced-Building/dp/B01E78WKEO/ref=sr_1_107?dchild=1&keywords=technic&qid=1592942043&sr=8-107
- 9396: https://www.amazon.com/LEGO-9396-Technic-Helicopter/dp/B006ZS4SHC/ref=pd_pg_c_d_dps_0_12?_encoding=UTF8&pd_rd_i=B006ZS4SHC&pd_rd_r=bc90ae49-7a06-4056-b63f-775136e793b9&pd_rd_w=xYilR&pd_rd_wg=vFxmQ&pf_rd_p=79ba09e2-b819-4ad0-84ae-fda224067c95&pf_rd_r=

Q3HDY12G2803JDNZA5Y3&psc=1&refRID=Q3HDY12G2803JDNZA5Y3

https://docs.google.com/document/d/1IUfoLXMBhwVEoiUfKIMzeYL0BS7pvVrb9eXbZtov2QA/edit

**Comment by ckoroma** [comment]
Talked with Florence and Kristi about possibilities for bringing on talent that is not already on the team.  Will follow up and post updates here.

Once I know the steps will reach out to the contacts shared.

**Comment by ckoroma** [comment]
Dan Flack CTR added too the build team today. Ordering the LEGO Technic Helicopter 9396 to send to him to begin building.

**Comment by ckoroma** [comment]
Kam Tillman added as the 4th builder: kat1862@utulsa.edu. 
Added him to engineering meetings and shipping LEGO Technic Heavy Lift Helicopter 42052

-interviewing marine candidates for testing and evaluation of models and VR spaces
